### ISSUE TITLE
Apply global tokens on a per-index basis

### ISSUE THREAD

**Issue by lizziegooding** [mapbox/carmen#780] opened 2018-11-07 18:26 UTC
### Context
As part of https://github.com/mapbox/carmen/pull/777, I noticed that autocomplete results dramatically changed when querying `sunset district`, a neighborhood in SF. Specifically, the query `Sunset Distr` returns very different results than `Sunset Dist` or `Sunset Distri`.
![sunset-district](https://user-images.githubusercontent.com/18095166/48151445-4f186680-e28f-11e8-8256-e2ea29e5643e.gif)

Carmen tokenizes the query `Sunset Distr` as `sunset", "di",  "str"`, breaking `str` from `distr` because of `str` at the end of a word is a global token https://github.com/mapbox/geocoder-abbreviations/blob/8be46333fd22d81006b6c52c36c37ff6efe10ea9/tokens/global.js#L8

`di` gets fuzzy matched to `dr`, `str` autocompletes to `street`, and so we return results like `Sunset Dr St, Saint Charles, Minnesota 55972`. 

## Proposed change
This is a big lift, but we should make it possible to apply global tokens only to specific indexes. In this case, we should only tokenize `<something>str` as `<something>` `str` for features in our German address index.

### Next Steps
Scope this project, prioritize amongst other competing priorities.

cc @mapbox/search

**Comment by apendleton** [comment] 2019-03-12 17:09
Done in #826 . There's still a very narrow circumstance under which token replacements need to be global -- the approach in #826 can't handle replacements on a per-index basis that rearrange the order of tokens in a query -- but as far as we know, all of the concrete strange behaviors caused by global replacements such as the one described above with Sunset District are resolved. Going to close this, but should the last corner case become a problem at some point in the future, we can reopen or cut a new ticket.

**Closed by apendleton** 2019-03-12 17:09 UTC
